### ISSUE TITLE
Including non-package example data

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/BiocWorkshops#13]
I've a small (3 kb) HDF5 file I'd like to include as part of my workshop.
Is this permitted?
If so, should I follow something like https://github.com/Bioconductor/BiocWorkshops/issues/12#issuecomment-401114526?

**Comment by lwaldron** [comment]
As long as Bookdown can build it, I don't see any reason why not. I am inclined to put >~10MB data files elsewhere, but for smaller files it seems convenient to put them here in a subdirectory like Issue #12 .

**Comment by PeteHaitch** [comment]
Confirming this works (locally). Implemented in db5c813158e069474cca296ea226ca56a44a9056
