### ISSUE TITLE
Including data from a non-Bioc package

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/BiocWorkshops#16]
I have data from a previous tutorial in a package available through GitHub but not Bioc. Can we somehow integrate that using devtools or something?

**Comment by lwaldron** [comment]
Do you mean having a "lawremi/myrepo" import? I don't see why not, but @lshep is building the conference AMIs and would know better than me. There have been GitHub dependencies for workshops in the past.

**Comment by lshep** [comment]
Yes adding github package dependencies shouldn't be an issue for us on the AMI.  I don't know how well that plays with Bookdown if there are examples in the bookdown document that would use it?

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
We'd add these dependencies in the `.travis.yml` and `DESCRIPTION` files.
In the `.travis.yml` there is a section for `r_github_packages`. Repos can be added there.

**Comment by drisso** [comment]
You may also need to add a `Remotes:` section in the DESCRIPTION file. See e.g., our workshop tutorial from last year (when slingshot was not yet in Bioconductor):
https://github.com/fperraudeau/bioc2017singlecell/blob/master/DESCRIPTION

**Comment by lshep** [comment]
@drisso I believe this is exactly the case for the new r_github_packages @LiNk-NY just mentioned

**Comment by lshep** [comment]
probably a good idea @LiNk-NY do you agree this is needed in the DESCRIPTION too?

**Comment by LiNk-NY** [comment]
Yes, I guess it wouldn't hurt and may be preferable to modifying the `.travis.yml` file. :+1:
