### ISSUE TITLE
Using package hosted on github for helper code

### ISSUE THREAD

**Issue by p-smirnov** [Bioconductor/BiocWorkshops#20]
I wanted to follow up on the the discussion from issue #16. For the pharmacogenomics ML workshop, @zhaleh-safikhani developed a package with some helper code that does things such as running Cross Validation and plotting the ML results. The package is hosted on github at bhklab/PharmacoGxML. We don't have plans to make this package available on BioC, since its just the helper functions for the workshop.

The question we wanted to is how important it is to keep the markdown document as a self-contained file? There are a handful of largely uninteresting function definitions in that package, which we could in theory include in the markdown to make a self contained document and remove the dependency. However, the large blocks of code distract from the legibility and content in our opinion. If I interpret @zhaleh-safikhani's intent correctly, the idea behind the workshop isn't necessarily to describe basic machine learning concepts, but to point out the challenges in applying them to these pharmacogenomic data types and how to get started with your analysis in this field. 

We also depend on another package (bhklab/mCI) we are hoping to push out soon for a method recently developed in the lab, but its also currently only on github. Is there anything we need to do except edit the Imports and Remotes fields of the description for the document to build?

**Comment by lwaldron** [comment]
Hi @p-smirnov, it's fine to depend on packages in GitHub, just include it in the Imports and Remotes fields of the DESCRIPTION like you mentioned. The Rmd markdown document here has to be self-contained only in that it has to build as part of this Bookdown project.

**Comment by lwaldron** [comment]
Let's keep this discussion on #16 .
