### ISSUE TITLE
Coetzee_StatePaintR.Rmd

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#25]
I'm creating an issue for each workshop, to be closed when both 1) the workshop is complete, and 2) it compiles without problems. Please note problems and status updates here.

**Comment by lwaldron** [comment]
@Simon-Coetzee please make a commit!

**Comment by lwaldron** [comment]
@Simon-Coetzee please accept your collaborator invitation so I can assign this card to you.

**Comment by LiNk-NY** [comment]
@Simon-Coetzee there is a formatting issue in your `Rmd` file. Please fix it. Thank you, MR.
