### ISSUE TITLE
Lee_Plyranges.Rmd

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#31]
I'm creating an issue for each workshop, to be closed when both 1) the workshop is complete, and 2) it compiles without problems. Please note problems and status updates here.

error use dplyr::filter

**Comment by lwaldron** [comment]
error use dplyr::filter

**Comment by sa-lee** [comment]
I think the dplyr::filter shouldn't be a problem since plyranges exports the dplyr generics, I think the error in that chunk was due to me having a typo in primary_tcells object. I've fixed it now and it knits on my computer.

**Comment by sa-lee** [comment]
@lwaldron I think my workshop is moslty complete now - let me know if there's anymore problems 😄

**Comment by LiNk-NY** [comment]
It looks like  a certain section is taking a really long time in the builder. Can you cut this example down to a more portable size? 

```
require("rtracklayer")
downloading 1 resources
retrieving 1 resource
loading from cache 
    '/home/user//.AnnotationHub/38894'
downloading 1 resources
retrieving 1 resource
loading from cache 
    '/home/user//.AnnotationHub/38895'
```

Thanks,
MR

**Comment by sa-lee** [comment]
Is it lines 557-560 or lines 585 - 597 where I read in the BigWig files:
```{r}
# a function to read our bigwig files
read_chr10_scores <- function(file) {
  read_bigwig(file, overlap_ranges = chr10_ranges) %>% 
    set_genome_info(genome = "hg19")
}
# apply the function to each file
chr10_scores <- lapply(bw_files, read_chr10_scores) 
# bind the ranges to a single GRAnges object
# and add a column to identify the ranges by signal type
chr10_scores <- bind_ranges(chr10_scores, .id = "signal_type")
chr10_scores
```
 I would've thought the resources from AnnotationHub would be cached on the build machine so getting them out wouldn't take so long?

**Comment by LiNk-NY** [comment]
I'm not sure how the build machines will be set up. Perhaps Lori @lshep can provide some input. 
They are now cached in our server build. It looks like your workshop is running fine now. Thanks.

**Comment by sa-lee** [comment]
Great thanks! Let me know and I can change it to something that's a bit quicker.

**Comment by sa-lee** [comment]
Also I've noticed that bookdown doesn't seem to render pdf images https://bioconductor.github.io/BiocWorkshops/fluent-genomic-data-analysis-with-plyranges.html#what-are-granges-objects

**Comment by LiNk-NY** [comment]
Hi Stuart, @sa-lee 
I know for sure that `png` and `svg` work. 
Regards,
Marcel

**Comment by LiNk-NY** [comment]
Note: `svg` won't render _easily_ in PDF format.
