### ISSUE TITLE
MacDonald_Annotation.Rmd

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#32]
I'm creating an issue for each workshop, to be closed when both 1) the workshop is complete, and 2) it compiles without problems. Please note problems and status updates here.

**Comment by LiNk-NY** [comment]
```
Quitting from lines 535-539 (MacDonald_Annotation.Rmd) 
Error in result_create(conn@ptr, statement) : 
  external pointer is not valid
Calls: local ... .local -> new -> initialize -> initialize -> result_create
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile MacDonald_Annotation.Rmd
Calls: <Anonymous> ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
Execution halted

Exited with status 1.

```

**Comment by lshep** [comment]
I just pulled down the entire BiocWorkshops and rendered and it is not showing any such error?

**Comment by LiNk-NY** [comment]
I've re-installed `Organism.dplyr` but that does not fix the issue. @jmacdon

**Comment by lshep** [comment]
I can't reproduce this locally -  when I pull this repo and do /home/lori/bin/R-3-5-branch/bin/Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')" locally it builds fine.

**Comment by LiNk-NY** [comment]
I'll delete the cache folder and re-run. @lshep It would be good to disable the cache in those particular code chunks.

**Comment by LiNk-NY** [comment]
It looks like that did the trick.
