### ISSUE TITLE
Ramos_MultiAssayExperiment.Rmd

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#33]
I'm creating an issue for each workshop, to be closed when both 1) the workshop is complete, and 2) it compiles without problems. Please note problems and status updates here.

**Comment by LiNk-NY** [comment]
Hey Levi, @lwaldron 
Is there something I left out of the workshop? 
Thanks, 
MR

**Comment by lwaldron** [comment]
Yes @LiNk-NY , some suggestions - and I'll include as many as you can finish by Weds in the CSAMA workshop this Thursday. I can help out with it between now and then too.

* additional text in the captions to explain the SE, MAE, and RE figures
* use suppressPackageStartupMessages()
* section **Working with RaggedExperiment**: more introductory text to explain what it is, when and how you use RE
    + note similarities with SummarizedExperiment
* `example(GRangesList)` - can you shorten this? The output is very long
* *Assay functions - introductory paragraph needed
* Working with MultiAssayExperiment - introductory paragraph needed
    + note similarities with SummarizedExperiment - maybe a table showing functions in common, e.g. rows for functions and columns for SE, RE, and MAE, with checkboxes where the function is implemented?
* add the cheat sheet as an image
* for `curatedTCGAData(..., dry.run=FALSE)`, hide ExperimentHub output
* Start TCGAUtils section by doing simplifcation of `acc` object
* Demo UUID conversion
* Demo filtering and separating by sample type (e.g. 1: solid tumors only, 2: split apart different sample types as different ExperimentList objects)

**Comment by LiNk-NY** [comment]
Thanks Levi @lwaldron. I've modified your comment to create a checklist.

**Comment by lwaldron** [comment]
Thanks @LiNk-NY, these are great improvements. Can you clarify this statement?

[] **Note**: Coercion to `SummarizedExperiment` is possible.

**Comment by lwaldron** [comment]
The API cheat sheet image does not make it into the bookdown @LiNk-NY

**Comment by LiNk-NY** [comment]
I fixed this. Thanks.
