### ISSUE TITLE
Safikhani_Pharmacogenomics.Rmd

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#34]
I'm creating an issue for each workshop, to be closed when both 1) the workshop is complete, and 2) it compiles without problems. Please note problems and status updates here.

**Comment by lwaldron** [comment]
Thanks @zhaleh-safikhani ! Quick note - you should remove lines like these:

```
source('http://bioconductor.org/biocLite.R')
biocLite('PharmacoGx')

library(devtools)
devtools::install_github("bhklab/mci")
devtools::install_github("bhklab/PharmacoGx-ML")
```

and instead add all dependencies in the DESCRIPTION file: The GitHub ones in `Remotes:`, the Bioconductor/CRAN ones in `Imports:`. This will ensure the dependencies are available on the AMIs and machine where the book is built.

**Comment by zhaleh-safikhani** [comment]
Done! 
Thanks for the note @lwaldron. 
I've added all the dependencies to DESCRIPTION already however I had forgotten to remove the installation lines from the document.

**Comment by lwaldron** [comment]
Thanks @zhaleh-safikhani ! I'm getting the following error trying to build your workshop though:

```
Quitting from lines 107-110 (Safikhani_Pharmacogenomics.Rmd) 
Error in load(file.path(saveDir, pSetFileName)) : 
  error reading from connection
```

**Comment by zhaleh-safikhani** [comment]
@lwaldron usually that issue comes from incomplete/interrupted downloads. To make it work again you need to delete the PSet folder.

**Comment by lwaldron** [comment]
Seems to work @zhaleh-safikhani , thanks! One more thing, the "machine_learning" chunk takes a long time to run (it's been going 15 minutes for me and still working), so won't be practical for students to run. Can you use a limited feature set or something like this to speed it up?

**Comment by zhaleh-safikhani** [comment]
I agree @lwaldron. I try to shrink the problem as much as possible.

**Comment by LiNk-NY** [comment]
Could you create a workshop specific folder such as "Safikhani_Pharmacogenomics" instead of `PSets`? Thanks!

**Comment by lwaldron** [comment]
It's about ~500M of files, so they shouldn't be added to the GitHub repository:
```
PSets$ du -m *
246     CCLE.RData
230     GDSC.RData
1       PSets.csv
```

**Comment by lwaldron** [comment]
(But you could use `downloadPSet("CCLE", saveDir = file.path(".", "Safikhani_Pharmacogenomics") )` so participants will know the data come from your workshop.)

BTW I see another error now:

```
Quitting from lines 361-399 (Safikhani_Pharmacogenomics.Rmd) 
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases
Calls: <Anonymous> ... withVisible -> eval -> eval -> validation -> lm -> lm.fit
Execution halted
```

**Comment by lwaldron** [comment]
Remove LaTeX code, workshop should be in pure Rmd. E.g.:

```
\section{Limitations and Future direction}

\section{Session Info} This document was generated with the following R version and packages loaded:

  toLatex(sessionInfo())
```

**Comment by zhaleh-safikhani** [comment]
Thanks for the comments @lwaldron! I have updated the code to address them.
However, I do not get the error you mentioned on my machine.

**Comment by LiNk-NY** [comment]
BTW use markdown HTML headers instead of `\section{}` tags. The tags are not rendering as anything that markdown can recognize.
Example: `## Introduction`
