### ISSUE TITLE
Citations not displayed properly 

### ISSUE THREAD

**Issue by sa-lee** [Bioconductor/BiocWorkshops#39]
I noticed this on my workshop, and @mikelove's  and @drisso's workshops that references aren't being displayed properly.

For example: 
https://bioconductor.github.io/BiocWorkshops/rna-seq-data-analysis-with-deseq2.html#preparing-data-for-deseq2 
The citation key is being shown rather than author and year.  

I thought I would've got around this by specifying a bibliography argument in the yaml at the top of my Rmd but maybe that gets ignored when buidling the entire book. Maybe the bib files should be placed in _output.yml?

**Comment by LiNk-NY** [comment]
Please add `.bib` files in the `index.Rmd` file as shown in the referenced commit. Thanks.

**Comment by LiNk-NY** [comment]
Hi Stuart, @sa-lee 
This is an old build of the book.
We had some issues on our end with the build server.
I will be pushing up builds ASAP.

**Comment by lwaldron** [comment]
Citations in both these workshops seem rendered correctly now. The server building the book was missing pandoc-citeproc (https://github.com/rstudio/bookdown-demo/issues/2).
