### ISSUE TITLE
Bookdown PDF

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#45]
Gives a 404:

https://bioconductor.github.io/BiocWorkshops/BioC2018.pdf

**Comment by lwaldron** [comment]
Also the epub:

https://bioconductor.github.io/BiocWorkshops/BioC2018.epub

**Comment by seandavi** [comment]
I have gotten the epub to build, but not the PDF. Perhaps remove the PDF link for now and just regenerate the epub?

**Comment by lwaldron** [comment]
@mikelove do you know something about getting a PDF from bookdown?

**Comment by mikelove** [comment]
hmm, haven't done bookdown yet. for the genomicsclass we used pandoc

**Comment by sa-lee** [comment]
what's the error for rendering to PDF?

**Comment by LiNk-NY** [comment]
I've gone ahead and fixed the issues. You should be able to download the pdf version of the workshops.
