### ISSUE TITLE
Publish book on bookdown.org?

### ISSUE THREAD

**Issue by sa-lee** [Bioconductor/BiocWorkshops#48]
After the conference could also put the book on https://bookdown.org/? Might be a good way to promote Bioc to other R users.

**Comment by lwaldron** [comment]
I like this idea.

**Comment by lwaldron** [comment]
Although I am also kind of interested in https://leanpub.com, and providing the option of making a donation to the Bioconductor Foundation.

**Comment by sa-lee** [comment]
I think you could do both. For example, Roger Peng's book is both on bookdown and leanpub.

**Comment by LiNk-NY** [comment]
At least we have both formats available: PDF and EPUB. :+1:
