### ISSUE TITLE
Licensing of all material

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/BiocWorkshops#49]
I don't think we have an agreed-upon license. Having such a thing in place and having contributor signoff for that license is probably worth doing after the dust settles from the conference.

**Comment by lwaldron** [comment]
Of the Creative Commons licenses:

https://creativecommons.org/licenses/

I think the following one is appropriate, for maximum permissiveness while requiring attribution to the original authors. At least some of the material (RNAseq 123, https://f1000research.com/articles/5-1408/v1) is already published under this license.

Attribution 
CC BY

This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.

**Comment by lwaldron** [comment]
@mikelove @seandavi @lawremi @bhaibeka @PeteHaitch @vobencha @nturaga @risserlin @LiNk-NY @lgeistlinger @diyadas @drisso @dvantwisk @hpages @jmacdon @kstreet13 @lawremi @Liubuntu @lshep @mikelove @mtmorgan @npcooley @nturaga @risserlin @sa-lee @vobencha @zhaleh-safikhani :

I am proposing the following:

1. that the materials be published on Leanpub with an optional suggested donation of $40 to the Bioconductor Foundation, the non-profit that funds the Bioconductor conference and its travel scholarships.
2. that all materials in the workshop by licensed as Creative Commons CC BY (see below).

Let me know if you want to opt out, so your materials can be removed before further distribution.

https://creativecommons.org/licenses/

Attribution
CC BY

This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.

**Comment by omsai** [comment]
CC BY is nice because that's what the [Carpentries](https://carpentries.org/) for their lesson material and makes remixing e.g. a Data Carpentry lesson easy.

**Comment by diyadas** [comment]
Given the amount of work that went into these workshops, I am against CC0, which doesn't require attribution. I don't mind if anyone remixes it, but I'd prefer they do it with attribution.

**Comment by mtmorgan** [comment]
Sounds like there is agreement to use CC BY licensing. Should that be implemented, i.e., added to the workshop material?

**Comment by lwaldron** [comment]
CC BY added to README.md and index.Rmd.
