### ISSUE TITLE
Where and how to classify workshops within the respective RMD file?

### ISSUE THREAD

**Issue by lgeistlinger** [Bioconductor/BiocWorkshops#5]
Quoting from the `README`:

- _Use (200-series chapters) contains workshops emphasizing use of Bioconductor for common tasks_
- _Follow the numbering scheme for classifying your workshop_

Where and how am I supposed to annotate that within my RMD file?

Within the header or as a subheading?

**Comment by LiNk-NY** [comment]
Yes, there are a couple of ways to go about this. One is to imply the order via the `Rmd` file names (as above) and the other is to explicitly state the order via the `_bookdown.yml` file.

The organization can be done after or during workshop submission. 
The `_bookdown.yml` file should look something like: 

```
rmd_files: [
    "index.rmd",
    "intro.Rmd",
# Section 1
    "RNASeq.Rmd",
    "ChIPSeq.Rmd"
]
```

Regards,
Marcel

**Comment by LiNk-NY** [comment]
This seems to have been resolved. Closing the issue.
