### ISSUE TITLE
error in epub version

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#53]
On page 427, before start of functional enrichment chapter:

```
This page contains the following errors:

error on line 174 at column 9: error parsing attribute name
Below is a rendering of the page up to the first error.
```

**Comment by lwaldron** [comment]
Also in functional enrichment chapter, all content from section "A primer on terminology, existing methods & statistical theory" is missing in epub version (but not in pdf or html versions).

**Comment by lwaldron** [comment]
drug sensitivity plots start at top of page and go upwards, on page 774.

**Comment by seandavi** [comment]
Weird!

**Comment by lwaldron** [comment]
Closing this since we will not publish epub and pdf versions of the 2018 book. But we need to empower authors to check all three versions of their chapter when developing.
